#!/usr/bin/env bash
TOUCHPAD_STATE="$(synclient | grep TouchpadOff | cut -d'=' -f2 | sed -e 's/^[[:space:]]*//')"

if [ $TOUCHPAD_STATE -eq 1 ]
then
  TOUCHPAD_NEW_STATE=0
  echo "Touchpad is enabled."
else
  TOUCHPAD_NEW_STATE=1
  echo "Touchpad is disabled."
fi

synclient TouchpadOff=$TOUCHPAD_NEW_STATE
